/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab6p2_alejandrareyes;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author aleja
 */
public class principal_ extends javax.swing.JFrame {

    /**
     * Creates new form principal_
     */
    public principal_() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crearequipo = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_nombreequipo = new javax.swing.JTextField();
        tf_paisequipo = new javax.swing.JTextField();
        tf_estadioequipo = new javax.swing.JTextField();
        tf_ciudadequipo = new javax.swing.JTextField();
        bt_agrearequipo = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jd_crearjugador = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        bt_agregarjugador = new javax.swing.JButton();
        tf_nombrejugador = new javax.swing.JTextField();
        jspi_edad = new javax.swing.JSpinner();
        cb_posicion = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jd_transferencias = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_jugadores = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtree_equipos = new javax.swing.JTree();
        bt_transferir = new javax.swing.JButton();
        popup_equipos = new javax.swing.JPopupMenu();
        jmi_eliminar = new javax.swing.JMenuItem();
        popup_jugadores = new javax.swing.JPopupMenu();
        jmi_modificar = new javax.swing.JMenuItem();
        jm_eliminarjugador = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        bt_crearequipos = new javax.swing.JButton();
        bt_crearjugadores = new javax.swing.JButton();
        bt_transferencia = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmi_crearequipos = new javax.swing.JMenuItem();
        jmi_crearjugadores = new javax.swing.JMenuItem();
        jmi_transferencias = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Crear Equipo");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre del Equipo");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Pais del Equipo");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Estadio");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Ciudad");

        bt_agrearequipo.setBackground(new java.awt.Color(0, 0, 0));
        bt_agrearequipo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        bt_agrearequipo.setText("Agregar");
        bt_agrearequipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agrearequipoMouseClicked(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab6p2_alejandrareyes/boroa_futbol (1).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(116, 116, 116)))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_paisequipo, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_estadioequipo, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nombreequipo, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_ciudadequipo, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(bt_agrearequipo)))
                .addGap(81, 81, 81))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel3)))
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_paisequipo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_nombreequipo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_ciudadequipo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_estadioequipo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(bt_agrearequipo)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_crearequipoLayout = new javax.swing.GroupLayout(jd_crearequipo.getContentPane());
        jd_crearequipo.getContentPane().setLayout(jd_crearequipoLayout);
        jd_crearequipoLayout.setHorizontalGroup(
            jd_crearequipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_crearequipoLayout.setVerticalGroup(
            jd_crearequipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Crear Jugador");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Edad");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Nombre");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Posicion");

        bt_agregarjugador.setBackground(new java.awt.Color(0, 0, 0));
        bt_agregarjugador.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bt_agregarjugador.setText("Agregar");
        bt_agregarjugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregarjugadorMouseClicked(evt);
            }
        });

        jspi_edad.setModel(new javax.swing.SpinnerNumberModel(15, 15, 45, 1));

        cb_posicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Portero", "Defensa", "Mediocampista", "Delantero" }));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab6p2_alejandrareyes/boroa_futbol (1).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addGap(88, 88, 88)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombrejugador)
                            .addComponent(jspi_edad)
                            .addComponent(cb_posicion, 0, 186, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(bt_agregarjugador)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_nombrejugador, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jspi_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cb_posicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(bt_agregarjugador)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab6p2_alejandrareyes/boroa_futbol (1).jpg"))); // NOI18N

        javax.swing.GroupLayout jd_crearjugadorLayout = new javax.swing.GroupLayout(jd_crearjugador.getContentPane());
        jd_crearjugador.getContentPane().setLayout(jd_crearjugadorLayout);
        jd_crearjugadorLayout.setHorizontalGroup(
            jd_crearjugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jd_crearjugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_crearjugadorLayout.createSequentialGroup()
                    .addGap(303, 303, 303)
                    .addComponent(jLabel17)
                    .addContainerGap(278, Short.MAX_VALUE)))
        );
        jd_crearjugadorLayout.setVerticalGroup(
            jd_crearjugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jd_crearjugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_crearjugadorLayout.createSequentialGroup()
                    .addGap(228, 228, 228)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(206, Short.MAX_VALUE)))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Transferencias");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Jugadores");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Equipos");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab6p2_alejandrareyes/boroa_futbol (1).jpg"))); // NOI18N

        jl_jugadores.setModel(new DefaultListModel());
        jl_jugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_jugadoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_jugadores);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Equipos");
        jtree_equipos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jtree_equipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtree_equiposMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtree_equipos);

        bt_transferir.setBackground(new java.awt.Color(255, 255, 51));
        bt_transferir.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        bt_transferir.setForeground(new java.awt.Color(0, 0, 0));
        bt_transferir.setText("Transferir -->");
        bt_transferir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_transferirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel16)
                .addGap(184, 184, 184)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64)
                .addComponent(bt_transferir)
                .addGap(83, 83, 83)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(164, 164, 164))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel13))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(bt_transferir)
                                .addGap(183, 183, 183))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_transferenciasLayout = new javax.swing.GroupLayout(jd_transferencias.getContentPane());
        jd_transferencias.getContentPane().setLayout(jd_transferenciasLayout);
        jd_transferenciasLayout.setHorizontalGroup(
            jd_transferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_transferenciasLayout.setVerticalGroup(
            jd_transferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jmi_eliminar.setText("Eliminar");
        jmi_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarActionPerformed(evt);
            }
        });
        popup_equipos.add(jmi_eliminar);

        jmi_modificar.setText("Modificar");
        jmi_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_modificarActionPerformed(evt);
            }
        });
        popup_jugadores.add(jmi_modificar);

        jm_eliminarjugador.setText("Eliminar\n");
        jm_eliminarjugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_eliminarjugadorActionPerformed(evt);
            }
        });
        popup_jugadores.add(jm_eliminarjugador);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Bienvenido a Boroa League Fantasy");

        jToolBar1.setBackground(new java.awt.Color(204, 204, 0));
        jToolBar1.setRollover(true);

        bt_crearequipos.setBackground(new java.awt.Color(204, 204, 0));
        bt_crearequipos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_crearequipos.setForeground(new java.awt.Color(0, 0, 0));
        bt_crearequipos.setText("Crear Equipos");
        bt_crearequipos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_crearequipos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_crearequipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearequiposMouseClicked(evt);
            }
        });
        bt_crearequipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crearequiposActionPerformed(evt);
            }
        });
        jToolBar1.add(bt_crearequipos);

        bt_crearjugadores.setBackground(new java.awt.Color(204, 204, 0));
        bt_crearjugadores.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_crearjugadores.setForeground(new java.awt.Color(0, 0, 0));
        bt_crearjugadores.setText("Crear Jugadores");
        bt_crearjugadores.setFocusable(false);
        bt_crearjugadores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_crearjugadores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_crearjugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearjugadoresMouseClicked(evt);
            }
        });
        bt_crearjugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crearjugadoresActionPerformed(evt);
            }
        });
        jToolBar1.add(bt_crearjugadores);

        bt_transferencia.setBackground(new java.awt.Color(204, 204, 0));
        bt_transferencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_transferencia.setForeground(new java.awt.Color(0, 0, 0));
        bt_transferencia.setText("Transferencias");
        bt_transferencia.setFocusable(false);
        bt_transferencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_transferencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_transferencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_transferenciaMouseClicked(evt);
            }
        });
        bt_transferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_transferenciaActionPerformed(evt);
            }
        });
        jToolBar1.add(bt_transferencia);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab6p2_alejandrareyes/boroa_futbol.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        jMenu1.setText("Opciones");

        jmi_crearequipos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmi_crearequipos.setText("Crear Equipos");
        jmi_crearequipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_crearequiposActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_crearequipos);

        jmi_crearjugadores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmi_crearjugadores.setText("Crear Jugadores");
        jmi_crearjugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_crearjugadoresActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_crearjugadores);

        jmi_transferencias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmi_transferencias.setText("Transferencias");
        jmi_transferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_transferenciasActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_transferencias);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_transferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_transferenciasActionPerformed
        jd_transferencias.pack();
        jd_transferencias.setLocationRelativeTo(this);
        jd_transferencias.setModal(true);
        jd_transferencias.setVisible(true);
    }//GEN-LAST:event_jmi_transferenciasActionPerformed

    private void bt_crearequiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crearequiposActionPerformed
        //
        
    }//GEN-LAST:event_bt_crearequiposActionPerformed

    private void bt_crearjugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crearjugadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_crearjugadoresActionPerformed

    private void bt_transferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_transferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_transferenciaActionPerformed

    private void bt_agregarjugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarjugadorMouseClicked
       //agregar bt
        DefaultListModel listajugadores = (DefaultListModel) jl_jugadores.getModel();
        listajugadores.addElement(new Jugador(tf_nombrejugador.getText(), (String) cb_posicion.getSelectedItem(), (Integer)jspi_edad.getValue()));
        
        jl_jugadores.setModel(listajugadores);
        tf_nombrejugador.setText("");
        cb_posicion.setSelectedIndex(0);
        jspi_edad.setValue(15);
        JOptionPane.showMessageDialog(jd_crearjugador, "Jugador creado exitosamente");
    }//GEN-LAST:event_bt_agregarjugadorMouseClicked

    private void jmi_crearequiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_crearequiposActionPerformed
        jd_crearequipo.pack();
        jd_crearequipo.setLocationRelativeTo(this);
        jd_crearequipo.setModal(true);
        jd_crearequipo.setVisible(true);
    }//GEN-LAST:event_jmi_crearequiposActionPerformed

    private void bt_crearequiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearequiposMouseClicked
        //boton crear equipos fuera del menu bar
        jd_crearequipo.pack();
        jd_crearequipo.setLocationRelativeTo(this);
        jd_crearequipo.setModal(true);
        jd_crearequipo.setVisible(true);
    }//GEN-LAST:event_bt_crearequiposMouseClicked

    private void bt_agrearequipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agrearequipoMouseClicked
        //boton agregar clicked
        DefaultTreeModel arbolequipos = (DefaultTreeModel) jtree_equipos.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) arbolequipos.getRoot();
        String temp_pais = tf_paisequipo.getText();
        int cont = 0;           
        for (int i = 0; i < raiz.getChildCount(); i++) {
            if (raiz.getChildAt(i).toString().equals(temp_pais)) {
                DefaultMutableTreeNode j = new DefaultMutableTreeNode(new Equipo(tf_nombreequipo.getText(), tf_paisequipo.getText(), tf_ciudadequipo.getText(), tf_estadioequipo.getText()));
                ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(j);
                cont++;
            }
        }
        if (cont == 0) {
          DefaultMutableTreeNode nuevopais = new DefaultMutableTreeNode(temp_pais);
          DefaultMutableTreeNode j = new DefaultMutableTreeNode(new Equipo(tf_nombreequipo.getText(), tf_paisequipo.getText(), tf_ciudadequipo.getText(), tf_estadioequipo.getText()));
          raiz.add(nuevopais); 
          nuevopais.add(j);
        }
        
        arbolequipos.reload();
        tf_ciudadequipo.setText("");
        tf_nombreequipo.setText("");
        tf_estadioequipo.setText("");
        tf_paisequipo.setText("");
        
        JOptionPane.showMessageDialog(jd_crearequipo, "Equipo creado exitosamente");

    }//GEN-LAST:event_bt_agrearequipoMouseClicked

    private void bt_crearjugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearjugadoresMouseClicked
        jd_crearjugador.pack();
        jd_crearjugador.setLocationRelativeTo(this);
        jd_crearjugador.setModal(true);
        jd_crearjugador.setVisible(true);
    }//GEN-LAST:event_bt_crearjugadoresMouseClicked

    private void jmi_crearjugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_crearjugadoresActionPerformed
        jd_crearjugador.pack();
        jd_crearjugador.setLocationRelativeTo(this);
        jd_crearjugador.setModal(true);
        jd_crearjugador.setVisible(true);
    }//GEN-LAST:event_jmi_crearjugadoresActionPerformed

    private void bt_transferenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_transferenciaMouseClicked
        jd_transferencias.pack();
        jd_transferencias.setLocationRelativeTo(this);
        jd_transferencias.setModal(true);
        jd_transferencias.setVisible(true);
    }//GEN-LAST:event_bt_transferenciaMouseClicked

    private void jtree_equiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtree_equiposMouseClicked
        //click derecho arbol
        
        if (evt.getButton() == 3){
            int row = jtree_equipos.getClosestRowForLocation(evt.getX(), evt.getY());
            jtree_equipos.setSelectionRow(row);
            
            Object nodo = jtree_equipos.getSelectionPath().getLastPathComponent();
            nodo_precionado = (DefaultMutableTreeNode) nodo;
            
            if (nodo_precionado.getUserObject() instanceof Equipo) {
                equipo = (Equipo) nodo_precionado.getUserObject();
                popup_equipos.show(evt.getComponent(),evt.getX(), evt.getY());
            }
        }
        
        
    }//GEN-LAST:event_jtree_equiposMouseClicked

    private void jmi_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarActionPerformed
        DefaultTreeModel arbolequipos = (DefaultTreeModel) jtree_equipos.getModel(); 
        arbolequipos.removeNodeFromParent(nodo_precionado);
        JOptionPane.showMessageDialog(jd_transferencias, "Equipo eliminado exitosamente");
    }//GEN-LAST:event_jmi_eliminarActionPerformed

    private void jl_jugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_jugadoresMouseClicked
        
          if (jl_jugadores.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                popup_jugadores.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
        
    }//GEN-LAST:event_jl_jugadoresMouseClicked

    private void jmi_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_modificarActionPerformed
        // modificar jugador
        if (jl_jugadores.getSelectedIndex() >= 0) {
            DefaultListModel listajugadores = (DefaultListModel) jl_jugadores.getModel();
            String msg = JOptionPane.showInputDialog("Nuevo nombre: " );
        String msg2 = JOptionPane.showInputDialog("Nueva edad: " );
        int msg2int = Integer.parseInt(msg2);
        
        
        
        while (nombretieneNums(msg)==false){
            JOptionPane.showMessageDialog(jd_transferencias, "El nombre no puede contener numeros");
            msg = JOptionPane.showInputDialog("Nuevo nombre: " );
        }
        
        while (msg2int<15 || msg2int>45 && edadtieneLetras(msg2)){
            JOptionPane.showMessageDialog(jd_transferencias, "La edad no puede ser menor de 15 o mayor de 45");
            msg2 = JOptionPane.showInputDialog("Nueva edad: " );
            msg2int = Integer.parseInt(msg2);
        }
        
        
        JOptionPane.showInputDialog("Nueva");
            ((Jugador) listajugadores.get(jl_jugadores.getSelectedIndex()) ). setNombre(JOptionPane.showInputDialog("nombre"));
            jl_jugadores.setModel(listajugadores);

        }
        
        
        
    }//GEN-LAST:event_jmi_modificarActionPerformed

    private void jm_eliminarjugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_eliminarjugadorActionPerformed
        //eliminar jugador
        
        if (jl_jugadores.getSelectedIndex() >= 0) {
            DefaultListModel listajugadores = (DefaultListModel) jl_jugadores.getModel();
           //((Jugador) listajugadores.get(jl_jugadores.getSelectedIndex())).remove);
            jl_jugadores.setModel(listajugadores);
        }
        
    }//GEN-LAST:event_jm_eliminarjugadorActionPerformed

    private void bt_transferirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_transferirMouseClicked
        if (jl_jugadores.getSelectedIndex() >= 0 ){
            DefaultTreeModel arbolequipos = (DefaultTreeModel) jtree_equipos.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) arbolequipos.getRoot();
           
            DefaultListModel listajugadores = (DefaultListModel) jl_jugadores.getModel();
            
            String nombre = ((Jugador) listajugadores.get(jl_jugadores.getSelectedIndex())).getNombre();
            String posicion = ((Jugador) listajugadores.get(jl_jugadores.getSelectedIndex())).getPosicion();
            int edad = ((Jugador) listajugadores.get(jl_jugadores.getSelectedIndex())).getEdad();
                      
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().equals(posicion)) {
                    //DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Persona(nombre,edad, nacionalidad));
                    //((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                } 
            }
            
            
            
            
        }
    }//GEN-LAST:event_bt_transferirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal_().setVisible(true);
            }
        });
    }
    
    public static boolean nombretieneNums (String cad){
        String regex = "^[a-z A-Z]";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(cad);
       return matcher.matches();
    }
    
    
    public static boolean edadtieneLetras (String cad){
        String regex = "^[1-4] + [1-5]";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(cad);
       return matcher.matches();
    }
    
    // falta validaciones, falta eliminar y modificar jugadores, 
  
    
  Equipo equipo;  
DefaultMutableTreeNode nodo_precionado;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_agrearequipo;
    private javax.swing.JButton bt_agregarjugador;
    private javax.swing.JButton bt_crearequipos;
    private javax.swing.JButton bt_crearjugadores;
    private javax.swing.JButton bt_transferencia;
    private javax.swing.JButton bt_transferir;
    private javax.swing.JComboBox<String> cb_posicion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDialog jd_crearequipo;
    private javax.swing.JDialog jd_crearjugador;
    private javax.swing.JDialog jd_transferencias;
    private javax.swing.JList<String> jl_jugadores;
    private javax.swing.JMenuItem jm_eliminarjugador;
    private javax.swing.JMenuItem jmi_crearequipos;
    private javax.swing.JMenuItem jmi_crearjugadores;
    private javax.swing.JMenuItem jmi_eliminar;
    private javax.swing.JMenuItem jmi_modificar;
    private javax.swing.JMenuItem jmi_transferencias;
    private javax.swing.JSpinner jspi_edad;
    private javax.swing.JTree jtree_equipos;
    private javax.swing.JPopupMenu popup_equipos;
    private javax.swing.JPopupMenu popup_jugadores;
    private javax.swing.JTextField tf_ciudadequipo;
    private javax.swing.JTextField tf_estadioequipo;
    private javax.swing.JTextField tf_nombreequipo;
    private javax.swing.JTextField tf_nombrejugador;
    private javax.swing.JTextField tf_paisequipo;
    // End of variables declaration//GEN-END:variables
}
